# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1314, 1034)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.OrtZeitClose = QtWidgets.QHBoxLayout()
        self.OrtZeitClose.setObjectName("OrtZeitClose")
        self.Location = QtWidgets.QComboBox(self.centralwidget)
        self.Location.setObjectName("Location")
        self.Location.addItem("")
        self.Location.addItem("")
        self.Location.addItem("")
        self.Location.addItem("")
        self.Location.addItem("")
        self.Location.addItem("")
        self.Location.addItem("")
        self.Location.addItem("")
        self.OrtZeitClose.addWidget(self.Location)
        spacerItem = QtWidgets.QSpacerItem(108, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.OrtZeitClose.addItem(spacerItem)
        self.Time = QtWidgets.QComboBox(self.centralwidget)
        self.Time.setObjectName("Time")
        self.Time.addItem("")
        self.Time.addItem("")
        self.Time.addItem("")
        self.OrtZeitClose.addWidget(self.Time)
        spacerItem1 = QtWidgets.QSpacerItem(118, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.OrtZeitClose.addItem(spacerItem1)
        self.Close = QtWidgets.QPushButton(self.centralwidget)
        self.Close.setObjectName("Close")
        self.OrtZeitClose.addWidget(self.Close)
        self.verticalLayout.addLayout(self.OrtZeitClose)
        self.Karte = QtWidgets.QHBoxLayout()
        self.Karte.setObjectName("Karte")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Karte.addItem(spacerItem2)
        self.Map = QtWidgets.QLabel(self.centralwidget)
        self.Map.setMinimumSize(QtCore.QSize(1280, 768))
        self.Map.setMaximumSize(QtCore.QSize(1280, 768))
        self.Map.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Map.setObjectName("Map")
        self.Karte.addWidget(self.Map)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Karte.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.Karte)
        self.BreiteLnge = QtWidgets.QHBoxLayout()
        self.BreiteLnge.setObjectName("BreiteLnge")
        self.Lon_Pos = QtWidgets.QLabel(self.centralwidget)
        self.Lon_Pos.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Lon_Pos.setAlignment(QtCore.Qt.AlignCenter)
        self.Lon_Pos.setObjectName("Lon_Pos")
        self.BreiteLnge.addWidget(self.Lon_Pos)
        self.Lat_Pos = QtWidgets.QLabel(self.centralwidget)
        self.Lat_Pos.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Lat_Pos.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Lat_Pos.setAlignment(QtCore.Qt.AlignCenter)
        self.Lat_Pos.setObjectName("Lat_Pos")
        self.BreiteLnge.addWidget(self.Lat_Pos)
        self.verticalLayout.addLayout(self.BreiteLnge)
        self.Kommentar = QtWidgets.QHBoxLayout()
        self.Kommentar.setObjectName("Kommentar")
        self.Position = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Position.setMaximumSize(QtCore.QSize(2000, 39))
        self.Position.setObjectName("Position")
        self.Kommentar.addWidget(self.Position)
        self.ClearPosition = QtWidgets.QPushButton(self.centralwidget)
        self.ClearPosition.setMinimumSize(QtCore.QSize(100, 36))
        self.ClearPosition.setMaximumSize(QtCore.QSize(72, 36))
        self.ClearPosition.setObjectName("ClearPosition")
        self.Kommentar.addWidget(self.ClearPosition)
        self.verticalLayout.addLayout(self.Kommentar)
        self.Startknopf = QtWidgets.QHBoxLayout()
        self.Startknopf.setObjectName("Startknopf")
        spacerItem4 = QtWidgets.QSpacerItem(208, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Startknopf.addItem(spacerItem4)
        self.StartMeasurement = QtWidgets.QPushButton(self.centralwidget)
        self.StartMeasurement.setObjectName("StartMeasurement")
        self.Startknopf.addWidget(self.StartMeasurement)
        spacerItem5 = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Startknopf.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.Startknopf)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Progress = QtWidgets.QProgressBar(self.centralwidget)
        self.Progress.setEnabled(True)
        self.Progress.setMinimum(0)
        self.Progress.setMaximum(48)
        self.Progress.setProperty("value", 0)
        self.Progress.setObjectName("Progress")
        self.horizontalLayout.addWidget(self.Progress)
        spacerItem6 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.amp_max = QtWidgets.QLabel(self.centralwidget)
        self.amp_max.setObjectName("amp_max")
        self.horizontalLayout.addWidget(self.amp_max)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1314, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.ClearPosition.clicked.connect(self.Position.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Location.setItemText(0, _translate("MainWindow", "CampusSüd"))
        self.Location.setItemText(1, _translate("MainWindow", "Kaiserstraße"))
        self.Location.setItemText(2, _translate("MainWindow", "Hbf"))
        self.Location.setItemText(3, _translate("MainWindow", "Gewerbegebiet"))
        self.Location.setItemText(4, _translate("MainWindow", "Neureut"))
        self.Location.setItemText(5, _translate("MainWindow", "Südstadt"))
        self.Location.setItemText(6, _translate("MainWindow", "Zoo"))
        self.Location.setItemText(7, _translate("MainWindow", "Schloss"))
        self.Time.setItemText(0, _translate("MainWindow", "Mittag"))
        self.Time.setItemText(1, _translate("MainWindow", "Abend"))
        self.Time.setItemText(2, _translate("MainWindow", "Nacht"))
        self.Close.setText(_translate("MainWindow", "Close"))
        self.Map.setText(_translate("MainWindow", "Map"))
        self.Lon_Pos.setText(_translate("MainWindow", "Breitengrad"))
        self.Lat_Pos.setText(_translate("MainWindow", "Längengrad"))
        self.Position.setPlaceholderText(_translate("MainWindow", "Straße/Kreuzung"))
        self.ClearPosition.setText(_translate("MainWindow", "Clear"))
        self.StartMeasurement.setText(_translate("MainWindow", "Start"))
        self.amp_max.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

