# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_Dauermessung.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1306, 1018)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.OrtZeitClose = QtWidgets.QHBoxLayout()
        self.OrtZeitClose.setObjectName("OrtZeitClose")
        self.Location = QtWidgets.QComboBox(self.centralwidget)
        self.Location.setObjectName("Location")
        self.Location.addItem("")
        self.Location.addItem("")
        self.Location.addItem("")
        self.Location.addItem("")
        self.Location.addItem("")
        self.Location.addItem("")
        self.Location.addItem("")
        self.Location.addItem("")
        self.Location.addItem("")
        self.Location.addItem("")
        self.OrtZeitClose.addWidget(self.Location)
        spacerItem = QtWidgets.QSpacerItem(108, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.OrtZeitClose.addItem(spacerItem)
        self.RepetitionRate = QtWidgets.QSpinBox(self.centralwidget)
        self.RepetitionRate.setMinimum(0)
        self.RepetitionRate.setProperty("value", 0)
        self.RepetitionRate.setObjectName("RepetitionRate")
        self.OrtZeitClose.addWidget(self.RepetitionRate)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.OrtZeitClose.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.OrtZeitClose.addItem(spacerItem1)
        self.NumberOfRepeats = QtWidgets.QSpinBox(self.centralwidget)
        self.NumberOfRepeats.setMinimum(1)
        self.NumberOfRepeats.setObjectName("NumberOfRepeats")
        self.OrtZeitClose.addWidget(self.NumberOfRepeats)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.OrtZeitClose.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.OrtZeitClose.addItem(spacerItem2)
        self.StartMeasurement = QtWidgets.QPushButton(self.centralwidget)
        self.StartMeasurement.setObjectName("StartMeasurement")
        self.OrtZeitClose.addWidget(self.StartMeasurement)
        spacerItem3 = QtWidgets.QSpacerItem(118, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.OrtZeitClose.addItem(spacerItem3)
        self.Close = QtWidgets.QPushButton(self.centralwidget)
        self.Close.setObjectName("Close")
        self.OrtZeitClose.addWidget(self.Close)
        self.verticalLayout_4.addLayout(self.OrtZeitClose)
        self.Karte = QtWidgets.QHBoxLayout()
        self.Karte.setObjectName("Karte")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Karte.addItem(spacerItem4)
        self.Map = QtWidgets.QLabel(self.centralwidget)
        self.Map.setMinimumSize(QtCore.QSize(1280, 768))
        self.Map.setMaximumSize(QtCore.QSize(1280, 768))
        self.Map.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Map.setObjectName("Map")
        self.Karte.addWidget(self.Map)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Karte.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.Karte)
        self.BreiteLnge = QtWidgets.QHBoxLayout()
        self.BreiteLnge.setObjectName("BreiteLnge")
        self.Lon_Pos = QtWidgets.QLabel(self.centralwidget)
        self.Lon_Pos.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Lon_Pos.setAlignment(QtCore.Qt.AlignCenter)
        self.Lon_Pos.setObjectName("Lon_Pos")
        self.BreiteLnge.addWidget(self.Lon_Pos)
        self.Lat_Pos = QtWidgets.QLabel(self.centralwidget)
        self.Lat_Pos.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Lat_Pos.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Lat_Pos.setAlignment(QtCore.Qt.AlignCenter)
        self.Lat_Pos.setObjectName("Lat_Pos")
        self.BreiteLnge.addWidget(self.Lat_Pos)
        self.verticalLayout_4.addLayout(self.BreiteLnge)
        self.Kommentar = QtWidgets.QHBoxLayout()
        self.Kommentar.setObjectName("Kommentar")
        self.Position = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Position.setMaximumSize(QtCore.QSize(2000, 39))
        self.Position.setObjectName("Position")
        self.Kommentar.addWidget(self.Position)
        self.ClearPosition = QtWidgets.QPushButton(self.centralwidget)
        self.ClearPosition.setMinimumSize(QtCore.QSize(100, 36))
        self.ClearPosition.setMaximumSize(QtCore.QSize(72, 36))
        self.ClearPosition.setObjectName("ClearPosition")
        self.Kommentar.addWidget(self.ClearPosition)
        self.verticalLayout_4.addLayout(self.Kommentar)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Wait = QtWidgets.QProgressBar(self.centralwidget)
        self.Wait.setProperty("value", 0)
        self.Wait.setInvertedAppearance(False)
        self.Wait.setObjectName("Wait")
        self.verticalLayout.addWidget(self.Wait)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Progress = QtWidgets.QProgressBar(self.centralwidget)
        self.Progress.setEnabled(True)
        self.Progress.setMinimum(1)
        self.Progress.setMaximum(15)
        self.Progress.setProperty("value", 1)
        self.Progress.setTextVisible(True)
        self.Progress.setInvertedAppearance(False)
        self.Progress.setObjectName("Progress")
        self.verticalLayout_2.addWidget(self.Progress)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Done = QtWidgets.QProgressBar(self.centralwidget)
        self.Done.setProperty("value", 0)
        self.Done.setObjectName("Done")
        self.verticalLayout_3.addWidget(self.Done)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1306, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.ClearPosition.clicked.connect(self.Position.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Location.setItemText(0, _translate("MainWindow", "CampusSüd"))
        self.Location.setItemText(1, _translate("MainWindow", "Kaiserstraße"))
        self.Location.setItemText(2, _translate("MainWindow", "Hbf"))
        self.Location.setItemText(3, _translate("MainWindow", "Gewerbegebiet"))
        self.Location.setItemText(4, _translate("MainWindow", "Schloss"))
        self.Location.setItemText(5, _translate("MainWindow", "Südstadt"))
        self.Location.setItemText(6, _translate("MainWindow", "Durlach"))
        self.Location.setItemText(7, _translate("MainWindow", "Industriegebiet"))
        self.Location.setItemText(8, _translate("MainWindow", "Agrafläche"))
        self.Location.setItemText(9, _translate("MainWindow", "Wald"))
        self.label.setText(_translate("MainWindow", "Wiederholungsrate [min]"))
        self.label_2.setText(_translate("MainWindow", "Wiederholungen"))
        self.StartMeasurement.setText(_translate("MainWindow", "Start"))
        self.Close.setText(_translate("MainWindow", "Close"))
        self.Map.setText(_translate("MainWindow", "Map"))
        self.Lon_Pos.setText(_translate("MainWindow", "Breitengrad"))
        self.Lat_Pos.setText(_translate("MainWindow", "Längengrad"))
        self.Position.setPlaceholderText(_translate("MainWindow", "Straße/Kreuzung"))
        self.ClearPosition.setText(_translate("MainWindow", "Clear"))
        self.Wait.setFormat(_translate("MainWindow", "%v/%m"))
        self.label_5.setText(_translate("MainWindow", "Zeit bis nächste Messung [min]"))
        self.label_3.setText(_translate("MainWindow", "Messung"))
        self.Done.setFormat(_translate("MainWindow", "%v/%m"))
        self.label_4.setText(_translate("MainWindow", "Anzahl durchgeführter Messungen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

